// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace AppCssNamespace {
    export interface IAppCss {
        app: string;
    }
}

declare const AppCssModule: AppCssNamespace.IAppCss;

export = AppCssModule;
