// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BoardCssNamespace {
    export interface IBoardCss {
        board: string;
    }
}

declare const BoardCssModule: BoardCssNamespace.IBoardCss;

export = BoardCssModule;
