// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BorderCssNamespace {
    export interface IBorderCss {
        border: string;
    }
}

declare const BorderCssModule: BorderCssNamespace.IBorderCss;

export = BorderCssModule;
