// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ControlsCssNamespace {
    export interface IControlsCss {
        controls: string;
        controls__icon: string;
        controls__item: string;
        controls__reset: string;
        controls__symbol: string;
    }
}

declare const ControlsCssModule: ControlsCssNamespace.IControlsCss;

export = ControlsCssModule;
