// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NavCssNamespace {
    export interface INavCss {
        nav: string;
    }
}

declare const NavCssModule: NavCssNamespace.INavCss;

export = NavCssModule;
