// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace PlayerSelectCssNamespace {
    export interface IPlayerSelectCss {
        checked: string;
        playerselect: string;
        playerselect__options: string;
        radiobutton: string;
    }
}

declare const PlayerSelectCssModule: PlayerSelectCssNamespace.IPlayerSelectCss;

export = PlayerSelectCssModule;
