// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace BoxCssNamespace {
    export interface IBoxCss {
        box: string;
    }
}

declare const BoxCssModule: BoxCssNamespace.IBoxCss;

export = BoxCssModule;
