// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NavLinksCssNamespace {
    export interface INavLinksCss {
        fadeIn: string;
        fadeOut: string;
        nav__links: string;
    }
}

declare const NavLinksCssModule: NavLinksCssNamespace.INavLinksCss;

export = NavLinksCssModule;
