// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NavIconCssNamespace {
    export interface INavIconCss {
        nav__icon: string;
        open: string;
    }
}

declare const NavIconCssModule: NavIconCssNamespace.INavIconCss;

export = NavIconCssModule;
