// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NavLinkCssNamespace {
    export interface INavLinkCss {
        nav__link: string;
    }
}

declare const NavLinkCssModule: NavLinkCssNamespace.INavLinkCss;

export = NavLinkCssModule;
